// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLZe9geKlR5p8izwpfx-Nxvq0uXGH1YO4',
    appId: '1:604958701776:web:cefa0a1d685de011dc06d5',
    messagingSenderId: '604958701776',
    projectId: 'workingtimo',
    authDomain: 'workingtimo.firebaseapp.com',
    storageBucket: 'workingtimo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzOeUM2befbFuY4QpxJ5Y30IPN4HknnlU',
    appId: '1:604958701776:android:50349b103ba7b850dc06d5',
    messagingSenderId: '604958701776',
    projectId: 'workingtimo',
    storageBucket: 'workingtimo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0PPXC-4pRm3IcbfICceludgMrzWGngPU',
    appId: '1:604958701776:ios:373959b452f7619ddc06d5',
    messagingSenderId: '604958701776',
    projectId: 'workingtimo',
    storageBucket: 'workingtimo.appspot.com',
    iosClientId: '604958701776-u0ptct163p451oc0af7091dduo2t2shg.apps.googleusercontent.com',
    iosBundleId: 'com.example.caldr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0PPXC-4pRm3IcbfICceludgMrzWGngPU',
    appId: '1:604958701776:ios:373959b452f7619ddc06d5',
    messagingSenderId: '604958701776',
    projectId: 'workingtimo',
    storageBucket: 'workingtimo.appspot.com',
    iosClientId: '604958701776-u0ptct163p451oc0af7091dduo2t2shg.apps.googleusercontent.com',
    iosBundleId: 'com.example.caldr',
  );
}
